### ISSUE TITLE
[Web Issue]: broken inside.java RSS feed

### ISSUE THREAD

**Issue by danthe1st** [java/devrel#13]
### What happened?

The RSS feed on inside.java is broken again.

Specifically, there's an error on (currently) column 1 of line 199.
![image](https://github.com/java/devrel/assets/34687786/6f148cf3-055a-4e5c-8c95-60e1c8c47e7b)
![image](https://github.com/java/devrel/assets/34687786/be30cd8e-482b-43c1-962d-a8afe6c61e8d)

When viewing the content in an editor, I see a unicode special character there.

The article this is happening is [JFR View Command - Sip of Java](https://inside.java/2023/09/26/sip082/).
The last code block (containing `Java Thread Statistics`) has an invalid unicode character.

### Steps to reproduce:
Go to https://inside.java/feed.xml
Observe that the XML content is not valid

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

custom RSS reader, Firefox, Chrome

**Comment by delabassee** [comment]
Thanks for spotting this @danthe1st 
The feed is now fixed.
