### ISSUE TITLE
[Bug]: Emoji character causes freeze

### ISSUE THREAD

**Issue by Thunderforge** [java/devrel#18]
### What happened?

If you just put the character 😄 in a text prompt and hit Run, the Playground freezes.

<img width="1134" alt="image" src="https://github.com/java/devrel/assets/6200170/ab5840ea-137c-4ae1-94ef-7e92922637e2">

For reference: doing this is JShell provides the following:

```
jshell> 😄
|  Error:
|  illegal character: '\ud83d\ude04'
|  😄
|  ^
|  Error:
|  reached end of file while parsing
|  😄
|    ^
```

### OS

macOS

### What browsers are you seeing the problem on?

Firefox

**Comment by delabassee** [comment]
Fixed.
