### ISSUE TITLE
[Typo] Minor date typo in "The Arrival of Java 22" article

### ISSUE THREAD

**Issue by Spring-0** [java/devrel#24]
### What happened?

In the "And the constant feature included in all JDK releases: Predictability" section, paragraph two:

_"Oracle will not offer long-term support for JDK 22; we will provide updates until September **2023** when it will be superseded by Oracle JDK 23."_

Year 2023 is behind us :)

Article Link: https://inside.java/2024/03/19/the-arrival-of-java-22/

### What OS are you seeing the problem on?

_Other_

**Comment by delabassee** [comment]
Fixed, thanks for spotting this.
