### ISSUE TITLE
[Web]: Wrong link in inside.java DOP v1.1 immutably and transparently --> Data and nothing but the Data

### ISSUE THREAD

**Issue by danthe1st** [java/devrel#26]
### What happened?

When viewing the [summary of `Model Data Immutably and Transparently - Data Oriented Programming v1.1`](https://inside.java/2024/05/27/dop-v1-1-immutable-transparent-data/#summary), the link `Model the data, the whole data, and nothing but the data - DOP v1.1` points to https://inside.java/2024/05/27/dop-v1-1-immutable-transparent-data/(/2024/05/29/DOP-v1-1-model-data) which doesn't exist. Instead, it should point to https://inside.java/2024/05/29/dop-v1-1-model-data/.

This is done correctly in [the first article of the series](https://inside.java/2024/05/23/dop-v1-1-introduction/#article-series).

### What OS are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Firefox

**Comment by nipafx** [comment]
Fixed, thanks for catching this, Dan. 😃
