### ISSUE TITLE
[Bug]: double slash in string causes a "string is not properly closed" error

### ISSUE THREAD

**Issue by derklaro** [java/devrel#27]
### What happened?

Hi! I was trying to quickly try something with the playground and stumbled upon the following issue: 

When trying to execute the following code snipping in the playgroud, I get an error report stating `A string is not properly closed`. However, as probably visisble, all string in the example are properly closed and the code executes just fine a regular jshell:
```java
System.out.println("https://google.de".concat("hello-world?x=y"));
```

```
|  Welcome to JShell -- Version 22.0.1
|  For an introduction type: /help intro

jshell> System.out.println("https://google.de".concat("hello-world?x=y"));
https://google.dehello-world?x=y
```

This seems to be somehow related to the double slash in the first string, as the following executes just fine:
```java
System.out.println("https:/google.de".concat("hello-world?x=y")); // works
System.out.println("/".concat("hello-world?x=y")); // works
System.out.println("//".concat("hello-world?x=y")); // doesn't work
```

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by delabassee** [comment]
Fixed in PG23
