### ISSUE TITLE
[Bug]: typo in playground sample name

### ISSUE THREAD

**Issue by j3graham** [java/devrel#28]
### What happened?

Samples/Records/Method Overrding 

Overrding -> Overriding

![IMG_0108](https://github.com/java/devrel/assets/8454305/88615451-c11f-4ae2-9004-0b09a39e4c16)

### OS

Other

### What browsers are you seeing the problem on?

Safari

### Additional information

Leave blank

**Comment by delabassee** [comment]
fixed
