### ISSUE TITLE
[Web]: "When to use Data-Oriented Programming v1.1" is positioned differently

### ISSUE THREAD

**Issue by danthe1st** [java/devrel#29]
### What happened?

All articles in the [DOP v1.1 series on inside.java](https://inside.java/2024/05/23/dop-v1-1-introduction/) contain a list of links to the other articles in that series in an "Article Series" or "Summary" section.

In the [When to use Data-Oriented Programming v1.1](https://inside.java/2024/06/10/dop-v1-1-wrap-up/), article, this list is missing at the bottom. Instead, it's present at the very top.

I don't know whether this should be fixed but it's kind of a weird inconsistency. For example, when someone wants to read all the articles sequentially, they might expect the next article to be listed at the end as this is the case with the other articles.

### What OS are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Firefox

**Comment by nipafx** [comment]
That's intentional. That blog post starts with a summary of what was discussed and it felt odd to not link to the respective articles there. And it felt even odder to repeat the list at the bottom.
