### ISSUE TITLE
[Bug]:  java.io.IO methods from JEP 477 aren't supported

### ISSUE THREAD

**Issue by cassandrus** [java/devrel#34]
### What happened?

I can't use preview feature "Implicitly Declared Classes and Instance Main Methods (Third Preview)":
![image](https://github.com/user-attachments/assets/6113c6d8-1ef1-43d6-a87a-cc8e835f7ebd)

I understand that perhaps you don't use implicit class under the hood, but playground looks like implicit class and IMO it should work like implicit class (even if needs to be simulated). More to say, playground is the place to try java, so it should support features for newbies and fast prototyping.

### OS

Windows

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave, Other

### Additional information

Leave blank

**Comment by JosePaumard** [comment]
Hello, indeed the Playground doesn't use implicit classes, it is based on JShell. So unfortunately this feature will not work. 
Sorry for the inconvenience.

**Comment by denismakogon** [comment]
Hi there from Playground team. @cassandrus! I want to inform you that methods from IO will be available in the upcoming Java Playground release. We already have a solution, we just need a little bit of time to present this to public audience.

I'll post and update to this ticket when we will deploy new changes.
