### ISSUE TITLE
[Request]: add auto complete

### ISSUE THREAD

**Issue by mhagnumdw** [java/devrel#35]
### What happened?

It would be really cool if it had auto complete.

### OS

Linux

**Comment by delabassee** [comment]
Thanks for the suggestion.
Indeed, auto-complete would indeed be nice but the Playground is not aiming to be some sort of online IDE. Adding such feature this would go against the simplicity and the lightweight nature of the Playground.

**Comment by delabassee** [comment]
See comment.
