### ISSUE TITLE
[Bug]: Emoji character results in "Something is wrong!? Please try again."

### ISSUE THREAD

**Issue by Thunderforge** [java/devrel#4]
### What happened?

The following source code

```java
var foo = "😄";
```

results in the error "Something is wrong!? Please try again." However, trying again produces the same error.

For reference: this is valid Java. Using JShell, I can write:

```java
jshell> var foo = "😄"
foo ==> "😄"
```

----

Related is that using an emoji anywhere in code produces the "Something is wrong!?" error message, rather than a more specific error message that might better describe the real problem. Here are some examples of invalid code that have their issues masked by "Something is wrong!?":

```java
var 😄 = "foo";
```

```java
System.out.😄("Hello world!")
```

```java
😄
```

### OS

macOS

### What browsers are you seeing the problem on?

Firefox

**Comment by delabassee** [comment]
this is now solved
