### ISSUE TITLE
[Bug]: Playground errors out at random times in mobile but desktop it is fine

### ISSUE THREAD

**Issue by rprabhu** [java/devrel#7]
### What happened?

I was playing around with the Java Playground, choosing different examples from the list. For some of the examples, it worked fine in my mobile but when I tried again for the same examples it failed throwing an error - "Something went wrong. Please try again". However, the error was occurring erratically with no specific steps to reproduce.

However, I did not encounter this error in the desktop.

Mobile Details
Redmi 9A
Android 10
Chrome

### OS

Other

### What browsers are you seeing the problem on?

Chrome

### Contact Details (optional)

rprabhu@duck.com

**Comment by delabassee** [comment]
Thanks for your feedback.

You were hitting 2 different issues at the same time: "Something went wrong" and mobile support. Regarding the later, making sure the PG works fine on mobile is important, and on our roadmap.

**Comment by delabassee** [comment]
Fixed.
