### ISSUE TITLE
[Bug]: Output can go out of bounds

### ISSUE THREAD

**Issue by danthe1st** [java/devrel#9]
### What happened?

When a line of the output is too long, the output dialog can go out of bounds with weird scrolling.

Example code:
```java
System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
```

Output field:
![image](https://github.com/java/devrel/assets/34687786/b4bacf1e-5ae8-4677-815f-93a068a9bba8)
when scrolling a bit to the right:
![image](https://github.com/java/devrel/assets/34687786/8064d491-5c24-48ab-beaf-6657fa21c4aa)

I would suggest to either add wrapping to the output field or allow horizontal scrolling inside it.

### OS

Windows

### What browsers are you seeing the problem on?

Firefox, Chrome

### Additional information

Leave blank

**Comment by delabassee** [comment]
Fixed. The console is now scrollabe.
